import jsdoc from "eslint-plugin-jsdoc"
import configPrettier from "eslint-config-prettier"
import globals from "globals"

export default [
  {
    ignores: ["node_modules/", "eslint.config.mjs", "build.mjs", "gulpfile.js"],
  },
  {
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.es2021,
        // Foundry VTT globals
        game: "readonly",
        Hooks: "readonly",
        CONFIG: "readonly",
        CONST: "readonly",
        foundry: "readonly",
        Actor: "readonly",
        Item: "readonly",
        ChatMessage: "readonly",
        Roll: "readonly",
        Dialog: "readonly",
        TextEditor: "readonly",
        renderTemplate: "readonly",
        fromUuid: "readonly",
        ui: "readonly",
        canvas: "readonly",
      },
      ecmaVersion: 2022,
      sourceType: "module",
    },
    plugins: {
      jsdoc,
    },
    rules: {
      "array-callback-return": "warn",
      "constructor-super": "error",
      "default-param-last": "warn",
      eqeqeq: ["warn", "smart"],
      "func-names": ["warn", "never"],
      "getter-return": "warn",
      "new-parens": ["warn", "always"],
      "no-alert": "warn",
      "no-array-constructor": "warn",
      "no-class-assign": "warn",
      "no-compare-neg-zero": "warn",
      "no-cond-assign": "warn",
      "no-const-assign": "error",
      "no-constant-condition": "warn",
      "no-constructor-return": "warn",
      "no-delete-var": "warn",
      "no-dupe-args": "warn",
      "no-dupe-class-members": "warn",
      "no-dupe-keys": "warn",
      "no-duplicate-case": "warn",
      "no-duplicate-imports": ["warn", { includeExports: true }],
      "no-empty": ["warn", { allowEmptyCatch: true }],
      "no-empty-character-class": "warn",
      "no-empty-pattern": "warn",
      "no-func-assign": "warn",
      "no-global-assign": "warn",
      "no-implicit-coercion": ["warn", { allow: ["!!"] }],
      "no-implied-eval": "warn",
      "no-import-assign": "warn",
      "no-invalid-regexp": "warn",
      "no-irregular-whitespace": "warn",
      "no-iterator": "warn",
      "no-lone-blocks": "warn",
      "no-loop-func": "warn",
      "no-misleading-character-class": "warn",
      "no-multi-str": "warn",
      "no-new-func": "warn",
      "no-object-constructor": "warn",
      "no-new-native-nonconstructor": "warn",
      "no-new-wrappers": "warn",
      "no-nonoctal-decimal-escape": "warn",
      "no-obj-calls": "warn",
      "no-octal": "warn",
      "no-octal-escape": "warn",
      "no-promise-executor-return": "warn",
      "no-proto": "warn",
      "no-regex-spaces": "warn",
      "no-script-url": "warn",
      "no-self-assign": "warn",
      "no-self-compare": "warn",
      "no-setter-return": "warn",
      "no-sequences": "warn",
      "no-template-curly-in-string": "warn",
      "no-this-before-super": "error",
      "no-unexpected-multiline": "warn",
      "no-unmodified-loop-condition": "warn",
      "no-unneeded-ternary": "warn",
      "no-unreachable": "warn",
      "no-unreachable-loop": "warn",
      "no-unsafe-negation": ["warn", { enforceForOrderingRelations: true }],
      "no-unsafe-optional-chaining": ["warn", { disallowArithmeticOperators: true }],
      "no-unused-expressions": "warn",
      "no-useless-backreference": "warn",
      "no-useless-call": "warn",
      "no-useless-catch": "warn",
      "no-useless-computed-key": ["warn", { enforceForClassMembers: true }],
      "no-useless-concat": "warn",
      "no-useless-constructor": "warn",
      "no-useless-escape": "warn",
      "no-useless-rename": "warn",
      "no-useless-return": "warn",
      "no-var": "warn",
      "no-void": "warn",
      "no-throw-literal": "error",
      "no-extra-boolean-cast": ["warn", { enforceForLogicalOperands: true }],
      "prefer-numeric-literals": "warn",
      "prefer-object-spread": "warn",
      "prefer-regex-literals": "warn",
      "prefer-spread": "warn",
      "prefer-template": "warn",
      "dot-notation": "warn",
      "one-var": ["warn", "never"],
      "symbol-description": "warn",
      "use-isnan": ["warn", { enforceForSwitchCase: true, enforceForIndexOf: true }],
      "valid-typeof": ["warn", { requireStringLiterals: true }],

      // JSDoc
      "jsdoc/check-access": "warn",
      "jsdoc/check-alignment": "warn",
      "jsdoc/check-param-names": "warn",
      "jsdoc/check-property-names": "warn",
      "jsdoc/check-tag-names": ["warn", { definedTags: ["category"] }],
      "jsdoc/check-types": "warn",
      "jsdoc/check-values": "warn",
      "jsdoc/empty-tags": "warn",
      "jsdoc/implements-on-classes": "warn",
      "jsdoc/no-bad-blocks": "warn",
      "jsdoc/require-description": "warn",
      "jsdoc/require-hyphen-before-param-description": ["warn", "never"],
      "jsdoc/require-jsdoc": "warn",
      "jsdoc/require-param": "warn",
      "jsdoc/require-param-name": "warn",
      "jsdoc/require-param-type": "warn",
      "jsdoc/require-property": "warn",
      "jsdoc/require-property-name": "warn",
      "jsdoc/require-property-type": "warn",
      "jsdoc/require-returns-check": "warn",
      "jsdoc/require-returns-type": "warn",
      "jsdoc/require-yields": "warn",
      "jsdoc/require-yields-check": "warn",
    },
    settings: {
      jsdoc: {
        preferredTypes: {
          ".<>": "<>",
        },
        mode: "typescript",
        tagNamePreference: {
          augments: "extends",
        },
      },
    },
  },
  configPrettier,
]
